# Generated by Django 4.2.7 on 2023-11-01 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField(default=18)),
                ("phone", models.CharField(max_length=50)),
                (
                    "addtime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 11, 1, 20, 7, 36, 67827)
                    ),
                ),
            ],
        ),
    ]
